version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./app/static/uploads:/app/app/static/uploads
      - ./instance:/app/instance
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=production
      - SECRET_KEY=${SECRET_KEY:-default-secret-key}
      - DB_TYPE=${DB_TYPE:-sqlite}
      - DB_USER=${DB_USER:-}
      - DB_PASSWORD=${DB_PASSWORD:-}
      - DB_HOST=${DB_HOST:-}
      - DB_PORT=${DB_PORT:-}
      - DB_NAME=${DB_NAME:-bulletin}
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: ${DB_IMAGE:-mysql:8.0}
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD:-rootpassword}
      - MYSQL_DATABASE=${DB_NAME:-bulletin}
      - MYSQL_USER=${DB_USER:-bulletin}
      - MYSQL_PASSWORD=${DB_PASSWORD:-password}
    ports:
      - "${DB_PORT:-3306}:3306"
    restart: unless-stopped

volumes:
  db_data: 