"""Add user profile fields

Revision ID: 1703868a6bed
Revises: e1af895747fa
Create Date: 2025-03-19 07:56:04.844548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1703868a6bed'
down_revision = 'e1af895747fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('location', sa.String(length=100), nullable=True))
    op.add_column('user', sa.Column('website', sa.String(length=200), nullable=True))
    op.add_column('user', sa.Column('newsletter_subscription', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('user', 'avatar',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=20),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'avatar',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.drop_column('user', 'updated_at')
    op.drop_column('user', 'created_at')
    op.drop_column('user', 'newsletter_subscription')
    op.drop_column('user', 'website')
    op.drop_column('user', 'location')
    # ### end Alembic commands ###
